# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift-Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift-Test
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'

  target 'RxSwift-TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwift-TestUITests' do
    # Pods for testing
  end

end
